# Dependabot configuration file
# Reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/auspice-client/"
    # If you want to run this manually, go to https://github.com/nextstrain/nextstrain.org/network/updates
    # and click "Recent update jobs" then "Check for updates".
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "auspice"
